// src/pages/NewItem.js
import React, { useState } from "react";
import API from "../utils/api";     // ← FIXED
import { useNavigate } from "react-router-dom";
import './NewItem.css';

export default function NewItem() {
  const [form, setForm] = useState({
    name: "",
    sku: "",
    rack: "Rack A1",
    totalStock: 0,
    rackStock: 0,
    threshold: 10,
    expiryDate: "",
  });
  const nav = useNavigate();

  function handleChange(e) {
    setForm({ ...form, [e.target.name]: e.target.value });
  }

  async function handleSubmit(e) {
    e.preventDefault();
    try {
      // 🔥 Only send allowed fields — backend assigns storeId + SKU
      const payload = {
        name: form.name,
        rack: form.rack,
        totalStock: form.totalStock,
        rackStock: form.rackStock,
        threshold: form.threshold,
        expiryDate: form.expiryDate,
      };

      await API.post("/items", payload);    // ← correct route & axios instance

      alert("Item created successfully!");
      nav("/items");
    } catch (err) {
      alert(err.response?.data?.error || err.message || "Failed to create item");
    }
  }

  return (
    <div className="newitem-page">
      <h1>New Item</h1>
      <form className="card form" onSubmit={handleSubmit}>
        
        <label>
          Name
          <input
            name="name"
            value={form.name}
            onChange={handleChange}
            placeholder="e.g., Blue Pen"
            required
          />
          <small>Human-readable name of the item.</small>
        </label>

        {/* ❗ UI kept, but backend ignores SKU */}
        <label>
          SKU
          <input
            name="sku"
            value={form.sku}
            onChange={handleChange}
            placeholder="e.g., BP-001"
          />
          <small>SKU will be auto-generated by backend.</small>
        </label>

        <label>
          Rack
          <input
            name="rack"
            value={form.rack}
            onChange={handleChange}
            placeholder="e.g., Rack A1"
          />
        </label>

        <label>
          Total Stock
          <input
            type="number"
            name="totalStock"
            value={form.totalStock}
            onChange={handleChange}
          />
        </label>

        <label>
          Rack Stock
          <input
            type="number"
            name="rackStock"
            value={form.rackStock}
            onChange={handleChange}
          />
        </label>

        <label>
          Threshold
          <input
            type="number"
            name="threshold"
            value={form.threshold}
            onChange={handleChange}
          />
        </label>

        <label>
          Expiry Date
          <input
            type="date"
            name="expiryDate"
            value={form.expiryDate}
            onChange={handleChange}
          />
        </label>

        <button className="btn" type="submit">
          Save Item
        </button>
      </form>
    </div>
  );
}
